apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-server
  template:
    metadata:
      labels:
        app: ollama-server
    spec:
      containers:
        - name: ollama-server
          image: ollama/ollama-server:latest
          ports:
            - containerPort: 11434
          #          command: [ "/bin/sh" ]
          #          args: [ "-c", "wget -O /models/gemma.model http://example.com/path/to/gemma.model && ./start-server.sh" ]
          volumeMounts:
            - name: model-volume
              mountPath: /models
      volumes:
        - name: model-volume
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  type: NodePort
  selector:
    app: ollama-server
  ports:
    - port: 8080
      targetPort: 11434
      nodePort: 30007