vaadin:
  launch-browser: true
spring:
  main:
    banner-mode: off
  application:
    name: spring-ai-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/samsoft
    username: user
    password: password
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        initialize-schema: true
        #        schema-name: my_schema
        schema-validation: true
    ollama:
      init:
        pull-model-strategy: WHEN_MISSING
      base-url: http://localhost:11434
      chat:
        enabled: true
        model: gemma3:4b
      embedding:
        enabled: true
        model: since2006/gte-Qwen2-7B-instruct:Q4_K_M
  servlet:
    multipart:
      max-file-size: 500MB
logging:
  level:
    root: warn
    com.samsoft: debug
    org.springframework.ai: info

server:
  port: 9090
management:
  readiness:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
